#!bin/bash/

cd ..

if [ ! -d git-game ]
then
echo "Bot directory not adjacent to git-game directory. Exiting"
cd Git-Hub-Bot
exit 1
fi

cd git-game
echo -e "Level 1\n======="
echo "$ git checkout 6402738"
git checkout 6402738

cd ..
cd Git-Hub-Bot

if [ $1 == "--finish" ]
then
bash task02 --finish
fi

exit 0